export const FILTER_TABS = [
  { id: 'all', label: 'All' },
  { id: 'live', label: 'Live' },
  { id: 'drafts', label: 'Drafts' },
  { id: 'shared', label: 'Shared with you' },
  { id: 'archived', label: 'Archived' },
];

export const WORKSPACES = [
  { id: 'all', label: 'All workspaces', color: null, count: null },
  { id: 'product', label: 'Product', color: '#3b82f6', count: 2 },
  { id: 'hr', label: 'HR', color: '#22c55e', count: 1 },
  { id: 'marketing', label: 'Marketing', color: '#f59e0b', count: 3 },
];

export const NAV_WORKSPACES = [
  { id: 'product', label: 'Product', color: '#3b82f6', count: 2 },
  { id: 'hr', label: 'HR', color: '#22c55e', count: 1 },
  { id: 'marketing', label: 'Marketing', color: '#f59e0b', count: 3 },
];

export const FORMS_DATA = [
  {
    id: 1,
    title: 'NPS Survey Q1 2026',
    status: 'live',
    responses: 248,
    timeAgo: '2d ago',
    workspace: 'product',
    gradientFrom: '#ebf2fb',
    gradientTo: '#b5d4f4',
    overlayColor: 'rgba(29,95,173,',
    iconGradient: 'linear-gradient(140deg, #ebf2fb 0%, #b5d4f4 100%)',
  },
  {
    id: 2,
    title: 'Onboarding Feedback',
    status: 'live',
    responses: 91,
    timeAgo: '5d ago',
    workspace: 'hr',
    gradientFrom: '#ebf5ee',
    gradientTo: '#9fe1cb',
    overlayColor: 'rgba(46,125,82,',
    iconGradient: 'linear-gradient(140deg, #ebf5ee 0%, #9fe1cb 100%)',
  },
  {
    id: 3,
    title: 'Bug Report Template',
    status: 'draft',
    responses: 0,
    timeAgo: '7h ago',
    workspace: 'product',
    gradientFrom: '#fef4e6',
    gradientTo: '#fac775',
    overlayColor: 'rgba(160,96,10,',
    iconGradient: 'linear-gradient(140deg, #fef4e6 0%, #fac775 100%)',
  },
  {
    id: 4,
    title: 'Exit Interview — HR',
    status: 'live',
    responses: 17,
    timeAgo: '2w ago',
    workspace: 'hr',
    gradientFrom: '#f0ebfb',
    gradientTo: '#c4adee',
    overlayColor: 'rgba(91,63,175,',
    iconGradient: 'linear-gradient(140deg, #f0ebfb 0%, #c4adee 100%)',
  },
  {
    id: 5,
    title: 'Product Feedback Survey',
    status: 'draft',
    responses: 0,
    timeAgo: '1m ago',
    workspace: 'product',
    gradientFrom: '#e8f6f5',
    gradientTo: '#6fd0ca',
    overlayColor: 'rgba(26,122,114,',
    iconGradient: 'linear-gradient(140deg, #e8f6f5 0%, #6fd0ca 100%)',
  },
  {
    id: 6,
    title: 'Marketing CSAT Q1',
    status: 'live',
    responses: 34,
    timeAgo: '3d ago',
    workspace: 'marketing',
    gradientFrom: '#fdf1ed',
    gradientTo: '#f5a58a',
    overlayColor: 'rgba(212,82,42,',
    iconGradient: 'linear-gradient(140deg, #fdf1ed 0%, #f5a58a 100%)',
  },
];
